### ISSUE TITLE
Exception and warning if the server does not respond

### ISSUE THREAD

**Issue by sollemar** [zerobounce/zero-bounce-php-sdk-setup#10]
Incorrect behavior when the server does not respond:

PHP Warning: Undefined array key 0 in ..../zero-bounce/sdk/src/ZeroBounce.php on line 471

Exception "No response" in ..../zero-bounce/sdk/src/ZeroBounce.php on line 456

Should give neither warning nor exception, but a correct error code, like "mail_server_did_not_respond" when the mail-server not respond

**Comment by vlungusst** [comment]
The server returns status code 200 and a json message for known errors. Any other response (including timeout) is unexpected behavior and will trigger an error in this wrapper.

**Comment by sollemar** [comment]
OK, but you have to fix the PHP warning

PHP Warning: Undefined array key 0 in ..../zero-bounce/sdk/src/ZeroBounce.php on line 471

Suggestion: Move $code = $this->getHttpCode($http_response_header); to line 451, after the check "is $json empty"

**Comment by aolariusst** [comment]
@sollemar does this look good? https://github.com/zerobounce/zero-bounce-php-sdk-setup/pull/11/files

**Comment by sollemar** [comment]
> @sollemar does this look good? https://github.com/zerobounce/zero-bounce-php-sdk-setup/pull/11/files

Yes, looks good for me.
