### ISSUE TITLE
Add public constant for available response statuses

### ISSUE THREAD

**Issue by JohJohan** [zerobounce/zero-bounce-php-sdk-setup#14]
Add public constant for available response statuses:
valid, invalid, catch-all, unknown, spamtrap, abuse, do_not_mail

That way as a develop your can use these constant to do logic in your code instead of checking on `valid` :
```php
if ('valid' === $response->status) {
 // do stuff
}
```

You can do:
```php
if (ZeroBounce::STATUS_RESPONSE_VALID === $response->status) {
 // do stuff
}
```

**Comment by VincentLanglet** [comment]
You mean this file https://github.com/zerobounce/zero-bounce-php-sdk-setup/blob/92d18d18b5cd638f34a2f4fb2facc2468dd79ccb/src/ZBValidateStatus.php#L5 ?

**Comment by JohJohan** [comment]
Yes thats it! I couldn't find it in the docs.
