### ISSUE TITLE
var_dump problem

### ISSUE THREAD

**Issue by furkankulaber** [zerobounce/zero-bounce-php-sdk-setup#3]
https://github.com/zerobounce-llc/zero-bounce-php-sdk-setup/blob/a3f2a6638977a2326e364886f443dad97f338175/src/ZeroBounce.php#L410

**Comment by Pfannkuchensack** [comment]
#4 fix for this.

**Comment by aolariusst** [comment]
Hi @furkankulaber,

We've also created a new release that includes this fix.

**Comment by furkankulaber** [comment]
@aolariusst thank you!
