### ISSUE TITLE
Missing urlencode

### ISSUE THREAD

**Issue by sollemar** [zerobounce/zero-bounce-php-sdk-setup#5]
https://github.com/zerobounce-llc/zero-bounce-php-sdk-setup/blob/master/src/ZeroBounce.php

Line 64

Missing urlencode for email, urlencode($email)

Without urlencode, email with + (e.g. name+test@gmail.com) get failed_syntax_check errors.

**Comment by aolariusst** [comment]
Hi @sollemar,

We've fixed this bug and also created a new release.
