### ISSUE TITLE
URGENT: Remove autoload-require

### ISSUE THREAD

**Issue by sollemar** [zerobounce/zero-bounce-php-sdk-setup#9]
https://github.com/zerobounce-llc/zero-bounce-php-sdk-setup/blob/master/src/ZeroBounce.php

Line 5

Remove

require_once __DIR__ . '/../vendor/autoload.php';

this is not necessary and crashes our application (we don't use "vendor" as dir-name)

**Comment by daniel-eppler-elaboratum** [comment]
I second that!

**Comment by yoX64** [comment]
Yes, we really need a fix for this.

**Comment by vlungusst** [comment]
Solved, apologies for the oversight and delay.
